version: 2.1

orbs:
  kube: circleci/kubernetes@0.11.0

jobs:
  "Docker build and push":
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo $DOCKER_PWD | docker login --username $DOCKER_USER --password-stdin
      - run: |
          gem install virtuatable:2.5.3
      - run: |
          pwd
      - run: |
          cd client && yarn install && yarn build
      - run: |
          pwd
      - run: |
          virtuatable docker create frontend --local
      - run: |
          pwd
  "Kubernetes deployment":
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
    steps:
      - checkout
      - kube/install-kubectl
      - run: |
           gem install faraday
      - run: |
          mkdir $HOME/.kube
      - run: |
          echo -n "${KUBERNETES_CONFIG}" | base64 --decode > $HOME/.kube/config
      - run: |
          ruby ./kubernetes/deploy.rb | kubectl apply -f -
workflows:
  version: 2.1
  build-deploy:
    jobs:
      - "Docker build and push":
          filters:
            branches:
              only: master
      - "Kubernetes deployment":
          requires:
            - "Docker build and push"
          filters:
            branches:
              only: master